### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-windows-process-tree#10]
@Tyriar from error telemetry (https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=de687ba5-8cd1-98c8-612d-2bea31e9853e):

```
RangeError: Maximum call stack size exceeded
at Array.findIndex (native)
at buildProcessTree (\node_modules.asar\windows-process-tree\lib\index.js:12:31) 
at rootPid.children.childIndexes.map.c (\node_modules.asar\windows-process-tree\lib\index.js:22:37) 
at Array.map (native)
at buildProcessTree (\node_modules.asar\windows-process-tree\lib\index.js:22:28) 
at rootPid.children.childIndexes.map.c (\node_modules.asar\windows-process-tree\lib\index.js:22:37) 
at Array.map (native)
at buildProcessTree (\node_modules.asar\windows-process-tree\lib\index.js:22:28) 
at rootPid.children.childIndexes.map.c (\node_modules.asar\windows-process-tree\lib\index.js:22:37) 
at Array.map (native)
```

**Comment by Tyriar** [comment]
This is odd that there's a spike in occurrences since March 8th

**Comment by Tyriar** [comment]
This error is weird as it's saying that there's a loop in a process/child process relationship. Regardless I think I'll add a max depth to search for just in case.
